"""
Layer 1 extraction schema. Fields that feed Layer 2 aggregation use fixed
enums, not free text, so counts/trends are meaningful across 8 years of
entries. See docs/ARCHITECTURE.md for the rationale.
"""

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class Emotion(str, Enum):
    SADNESS = "sadness"
    ANXIETY = "anxiety"
    ANGER = "anger"
    FRUSTRATION = "frustration"
    FEAR = "fear"
    JOY = "joy"
    GRATITUDE = "gratitude"
    LOVE = "love"
    LONELINESS = "loneliness"
    GUILT = "guilt"
    SHAME = "shame"
    HOPE = "hope"
    CALM = "calm"
    OVERWHELM = "overwhelm"


class CognitiveDistortion(str, Enum):
    CATASTROPHIZING = "catastrophizing"
    BLACK_AND_WHITE = "black_and_white"
    OVERGENERALIZATION = "overgeneralization"
    MENTAL_FILTERING = "mental_filtering"
    DISQUALIFYING_POSITIVE = "disqualifying_positive"
    MIND_READING = "mind_reading"
    FORTUNE_TELLING = "fortune_telling"
    MAGNIFICATION_MINIMIZATION = "magnification_minimization"
    EMOTIONAL_REASONING = "emotional_reasoning"
    SHOULD_STATEMENTS = "should_statements"
    LABELING = "labeling"
    PERSONALIZATION = "personalization"


class Theme(str, Enum):
    WORK = "work"
    FAMILY = "family"
    ROMANTIC = "romantic"
    FRIENDSHIP = "friendship"
    HEALTH = "health"
    FINANCES = "finances"
    SELF_IMAGE = "self_image"
    PURPOSE_MEANING = "purpose_meaning"
    OTHER = "other"


class CopingBehavior(str, Enum):
    EXERCISE = "exercise"
    SOCIAL_SUPPORT = "social_support"
    AVOIDANCE = "avoidance"
    SUBSTANCE_USE = "substance_use"
    CREATIVE_OUTLET = "creative_outlet"
    REST = "rest"
    PROBLEM_SOLVING = "problem_solving"
    ISOLATION = "isolation"
    SPIRITUALITY = "spirituality"


class RelationshipType(str, Enum):
    ROMANTIC_PARTNER = "romantic_partner"
    FAMILY_PARENT = "family_parent"
    FAMILY_SIBLING = "family_sibling"
    FAMILY_OTHER = "family_other"
    FRIEND = "friend"
    COLLEAGUE = "colleague"
    OTHER = "other"


class Valence(str, Enum):
    SUPPORTIVE = "supportive"
    CONFLICT = "conflict"
    NEUTRAL = "neutral"
    MIXED = "mixed"


class SleepQuality(str, Enum):
    GOOD = "good"
    POOR = "poor"
    NOT_MENTIONED = "not_mentioned"


class Stressor(BaseModel):
    category: Theme


class RelationshipMention(BaseModel):
    type: RelationshipType
    valence: Valence


class PhysicalHealth(BaseModel):
    sleep_quality: SleepQuality
    exercise_mentioned: bool
    substance_use_mentioned: bool


class RiskFlags(BaseModel):
    self_harm_language: bool
    hopelessness_language: bool


class EntryExtraction(BaseModel):
    """What the local LLM produces for a single entry. entry_id/date are
    attached afterward by the pipeline, not generated by the model, to
    avoid ID hallucination."""

    primary_emotions: list[Emotion] = Field(max_length=3)
    emotional_intensity: int = Field(ge=1, le=10)
    sentiment_score: float = Field(ge=-1.0, le=1.0)
    cognitive_distortions: list[CognitiveDistortion] = Field(default_factory=list)
    themes: list[Theme] = Field(max_length=4)
    stressors: list[Stressor] = Field(default_factory=list)
    relationships_mentioned: list[RelationshipMention] = Field(default_factory=list)
    coping_behaviors: list[CopingBehavior] = Field(default_factory=list)
    physical_health: PhysicalHealth
    notable_event: bool
    event_category: Optional[Theme] = None
    risk_flags: RiskFlags
    notable_detail: Optional[str] = Field(
        default=None,
        max_length=200,
        description="One short sentence of qualitative nuance, for human review only — never used in aggregation.",
    )
    confidence: float = Field(ge=0.0, le=1.0)
